# Generated by Django 4.2.14 on 2024-07-28 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('JobName', models.CharField(max_length=10)),
                ('WorkPlace', models.CharField(max_length=10)),
                ('WorkKind', models.CharField(max_length=10)),
                ('JobID', models.CharField(max_length=20)),
                ('JobDescrib', models.TextField(max_length=1000)),
                ('JObRequire', models.TextField(max_length=1000)),
            ],
        ),
    ]
