# Generated by Django 4.2.14 on 2024-07-28 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='JObRequire',
            new_name='JobRequire',
        ),
    ]
