# Generated by Django 4.2.14 on 2024-08-18 15:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobs', '0002_rename_jobrequire_job_jobrequire'),
    ]

    operations = [
        migrations.CreateModel(
            name='candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='姓名')),
                ('phone', models.CharField(max_length=20, verbose_name='电话')),
                ('email', models.CharField(max_length=20, verbose_name='邮箱')),
                ('job_wanted', models.CharField(max_length=250, verbose_name='求职意向')),
                ('education', models.CharField(max_length=1000, verbose_name='教育经历')),
                ('project', models.CharField(max_length=1000, verbose_name='项目经历')),
                ('award', models.CharField(blank=True, max_length=300, verbose_name='获得奖项')),
                ('social', models.CharField(max_length=300, verbose_name='社交账号')),
                ('evaluation', models.CharField(max_length=300, verbose_name='自我评价')),
                ('advantage', models.CharField(max_length=300, verbose_name='个人优势')),
                ('candidate_position', models.FileField(blank=True, upload_to='', verbose_name='简历位置')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
