# Generated by Django 4.2.14 on 2024-08-18 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_candidate'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='last_editTime',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='advantage',
            field=models.CharField(max_length=250, verbose_name='个人优势'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='award',
            field=models.CharField(blank=True, max_length=250, verbose_name='获得奖项'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='education',
            field=models.TextField(max_length=1000, verbose_name='教育经历'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='evaluation',
            field=models.CharField(max_length=250, verbose_name='自我评价'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='job_wanted',
            field=models.CharField(max_length=25, verbose_name='求职意向'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='project',
            field=models.TextField(max_length=1000, verbose_name='项目经历'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='social',
            field=models.CharField(max_length=250, verbose_name='社交账号'),
        ),
    ]
