# Generated by Django 4.2.14 on 2024-08-22 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_candidate_last_edittime_alter_candidate_advantage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='advantage',
            field=models.TextField(blank=True, max_length=1000, verbose_name='个人优势'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='education',
            field=models.TextField(blank=True, max_length=1000, verbose_name='教育经历'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='evaluation',
            field=models.TextField(blank=True, max_length=1000, verbose_name='自我评价'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='project',
            field=models.TextField(blank=True, max_length=1000, verbose_name='项目经历'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='social',
            field=models.CharField(blank=True, max_length=250, verbose_name='社交账号'),
        ),
    ]
