# Generated by Django 4.2.14 on 2024-07-28 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='person',
            name='major',
            field=models.CharField(choices=[('1', '软件工程'), ('2', '计算机科学'), ('3', '网络安全'), ('4', '电子信息'), ('5', '数学'), ('6', '统计学')], max_length=10),
        ),
    ]
