# Generated by Django 4.2.14 on 2024-08-23 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_interviewer'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewer',
            name='type',
            field=models.CharField(choices=[(0, '一面面试官'), (1, '二面面试官'), (2, '待定')], default='待定', max_length=20, verbose_name='面试官类型'),
        ),
    ]
