# Generated by Django 4.2.14 on 2024-08-23 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_interviewer_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewer',
            name='type',
            field=models.IntegerField(choices=[(0, '一面面试官'), (1, '二面面试官'), (2, '待定')], default=2, verbose_name='面试官类型'),
        ),
    ]
