# Generated by Django 4.2.14 on 2024-08-22 10:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('education_background', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(15)], verbose_name='教育背景得分')),
                ('project_experience', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)], verbose_name='项目经历得分')),
                ('profession_level', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)], verbose_name='专业水平得分')),
                ('learning_ability', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)], verbose_name='学习能力得分')),
                ('english_level', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='英语水平得分')),
                ('expression_ability', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='表达能力得分')),
                ('cooperation_ability', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='合作能力得分')),
                ('evaluation', models.TextField(verbose_name='面试官评价')),
                ('interview_name', models.CharField(max_length=20, verbose_name='面试官')),
                ('status', models.CharField(choices=[(0, '不建议录取'), (1, '建议录取'), (2, '建议进行二面')], default='待定', max_length=10)),
                ('last_editTime', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
