# Generated by Django 4.2.14 on 2024-08-23 03:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_interviewer'),
        ('interview', '0002_alter_interviewresult_status_resumesubmitrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumesubmitrecord',
            name='interviewer1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='FirstInterviewer', to='user.interviewer'),
        ),
        migrations.AddField(
            model_name='resumesubmitrecord',
            name='interviewer2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='SecondInterviewer', to='user.interviewer'),
        ),
        migrations.AlterField(
            model_name='resumesubmitrecord',
            name='interviweResult1',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='FirstInterviewResult', to='interview.interviewresult'),
        ),
        migrations.AlterField(
            model_name='resumesubmitrecord',
            name='interviweResult2',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='SecondInterviewResult', to='interview.interviewresult'),
        ),
    ]
