# Generated by Django 4.2.14 on 2024-08-23 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0003_resumesubmitrecord_interviewer1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumesubmitrecord',
            name='status',
            field=models.BooleanField(default=False, verbose_name='工单状态'),
        ),
    ]
