# Generated by Django 4.2.14 on 2024-08-23 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0004_resumesubmitrecord_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='qqGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qqGroupNum', models.CharField(max_length=20, verbose_name='qq群组号')),
                ('department', models.IntegerField(verbose_name='部门')),
            ],
        ),
    ]
