# Generated by Django 4.2.14 on 2024-08-23 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0005_qqgroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qqgroup',
            name='department',
            field=models.IntegerField(choices=[(0, '研发'), (1, '产品'), (2, '运营'), (3, '销售'), (4, '市场'), (5, '设计')], verbose_name='部门'),
        ),
        migrations.AlterField(
            model_name='resumesubmitrecord',
            name='final_grade',
            field=models.FloatField(blank=True, default=0, verbose_name='最终成绩'),
        ),
        migrations.AlterField(
            model_name='resumesubmitrecord',
            name='interviweResult1',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='FirstInterviewResult', to='interview.interviewresult'),
        ),
        migrations.AlterField(
            model_name='resumesubmitrecord',
            name='interviweResult2',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='SecondInterviewResult', to='interview.interviewresult'),
        ),
    ]
