# Generated by Django 4.2.14 on 2024-08-23 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_alter_candidate_advantage_alter_candidate_education_and_more'),
        ('interview', '0006_alter_qqgroup_department_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='resumesubmitrecord',
            unique_together={('job', 'department')},
        ),
    ]
