# Generated by Django 4.2.14 on 2024-08-23 16:20

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('interview', '0007_alter_resumesubmitrecord_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='resumesubmitrecord',
            unique_together={('user', 'department')},
        ),
    ]
