# Generated by Django 4.2.14 on 2024-08-24 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0008_alter_resumesubmitrecord_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qqgroup',
            name='department',
            field=models.CharField(max_length=20, verbose_name='部门'),
        ),
    ]
