# Generated by Django 4.2.14 on 2024-08-25 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0010_resumesubmitrecord_create_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resumesubmitrecord',
            old_name='interviweResult1',
            new_name='interviewResult1',
        ),
        migrations.RenameField(
            model_name='resumesubmitrecord',
            old_name='interviweResult2',
            new_name='interviewResult2',
        ),
    ]
