# Generated by Django 4.2.14 on 2024-08-25 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0011_rename_interviweresult1_resumesubmitrecord_interviewresult1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewresult',
            name='面试得分',
            field=models.FloatField(default=0),
        ),
    ]
