# Generated by Django 4.2.14 on 2024-08-25 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0012_interviewresult_面试得分'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewresult',
            name='面试得分',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
