# Generated by Django 4.2.14 on 2024-08-25 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0013_alter_interviewresult_面试得分'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interviewresult',
            name='面试得分',
        ),
        migrations.AddField(
            model_name='interviewresult',
            name='sumScore',
            field=models.FloatField(blank=True, null=True, verbose_name='面试得分'),
        ),
    ]
