# Generated by Django 4.2.14 on 2024-08-25 15:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('interview', '0014_remove_interviewresult_面试得分_interviewresult_sumscore'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewresult',
            name='type',
            field=models.IntegerField(choices=[(0, '一面面试官'), (1, '二面面试官'), (2, '待定')], default=2, verbose_name='面试类型'),
        ),
        migrations.AddField(
            model_name='interviewresult',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='interviewresult',
            unique_together={('user', 'type')},
        ),
    ]
