# Generated by Django 4.2.14 on 2024-08-26 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0015_interviewresult_type_interviewresult_user_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='interviewresult',
            unique_together=set(),
        ),
    ]
