# Generated by Django 4.2.14 on 2024-08-26 02:11

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('interview', '0016_alter_interviewresult_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='interviewresult',
            unique_together={('user', 'type')},
        ),
    ]
